name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      env:
        DB_HOST: localhost
        DB_NAME: purchase_orders_db
        DB_USER: root
        DB_PASSWORD: root
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-express-mysql-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-express-mysql-app:latest

    - name: Deploy to server (Optional)
      run: echo "Deploying to server"
      # Add your deployment steps here, like SSH or docker-compose commands
